//! GPS L2C CM ranging codes (IS-GPS-200). L2 CM is 10230 chips at 0.5115 Mcps
//! (a 20 ms period), generated by a 27-bit modular (Galois) shift register:
//!   shift(x) = (x >> 1) XOR ((x & 1) * 0o445112474);   chip = x & 1.
//! The per-PRN initial register state selects the code.
//!
//! The polynomial + init table are the authoritative GNSS-SDR values
//! (`GPS_L2C.h` / `gps_l2c_signal_replica.cc`, themselves from IS-GPS-200). The
//! test cross-checks the port against that reference (golden first-24 chips) and
//! against the code's exact 5115/10230 balance.

pub const CODE_LEN: usize = 10230;
const FEEDBACK: u32 = 0o445112474;

/// Per-PRN initial shift-register state (octal), PRN 1..=63.
const L2C_M_INIT: [u32; 63] = [
    0o742417664, 0o756014035, 0o2747144, 0o66265724,
    0o601403471, 0o703232733, 0o124510070, 0o617316361,
    0o47541621, 0o733031046, 0o713512145, 0o24437606,
    0o21264003, 0o230655351, 0o1314400, 0o222021506,
    0o540264026, 0o205521705, 0o64022144, 0o120161274,
    0o44023533, 0o724744327, 0o45743577, 0o741201660,
    0o700274134, 0o10247261, 0o713433445, 0o737324162,
    0o311627434, 0o710452007, 0o722462133, 0o50172213,
    0o500653703, 0o755077436, 0o136717361, 0o756675453,
    0o435506112, 0o771353753, 0o226107701, 0o22025110,
    0o402466344, 0o752566114, 0o702011164, 0o41216771,
    0o47457275, 0o266333164, 0o713167356, 0o60546335,
    0o355173035, 0o617201036, 0o157465571, 0o767360553,
    0o23127030, 0o431343777, 0o747317317, 0o45706125,
    0o2744276, 0o60036467, 0o217744147, 0o603340174,
    0o326616775, 0o63240065, 0o111460621,
];

#[inline]
fn shift(x: u32) -> u32 {
    (x >> 1) ^ ((x & 1) * FEEDBACK)
}

/// One 20 ms L2 CM ranging code (10230 chips) as +1.0 / -1.0. PRN 1..=63.
pub fn l2c_cm_code(prn: usize) -> Vec<f32> {
    assert!((1..=63).contains(&prn), "L2C PRN {prn} out of range (1..=63)");
    let mut x = L2C_M_INIT[prn - 1];
    (0..CODE_LEN)
        .map(|_| {
            let chip = (x & 1) as f32;
            x = shift(x);
            1.0 - 2.0 * chip
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn first24(prn: usize) -> u32 {
        let mut x = L2C_M_INIT[prn - 1];
        let mut v = 0u32;
        for _ in 0..24 {
            v = (v << 1) | (x & 1);
            x = shift(x);
        }
        v
    }

    // Golden first-24 chips from the authoritative GNSS-SDR generator (IS-GPS-200).
    #[test]
    fn matches_reference_first24_chips() {
        for (prn, want) in [
            (1, 0o12757036u32),
            (2, 0o50370043),
            (7, 0o7533713),
            (32, 0o60056052),
            (63, 0o45177224),
        ] {
            assert_eq!(first24(prn), want, "PRN {prn} first-24 mismatch");
        }
    }

    #[test]
    fn every_prn_is_exactly_balanced() {
        // an L2 CM code is exactly 5115/10230 zeros/ones — a correct-code signature
        for prn in 1..=63 {
            let ones = l2c_cm_code(prn).iter().filter(|&&v| v < 0.0).count();
            assert_eq!(ones, CODE_LEN / 2, "PRN {prn} ones {ones}");
        }
    }

    #[test]
    fn distinct_prns_are_nearly_orthogonal() {
        let a = l2c_cm_code(1);
        let b = l2c_cm_code(7);
        let x: f32 = a.iter().zip(&b).map(|(u, v)| u * v).sum();
        assert!(x.abs() < 0.06 * CODE_LEN as f32, "PRN1xPRN7 xcorr {x}");
        let peak: f32 = a.iter().map(|v| v * v).sum();
        assert!((peak - CODE_LEN as f32).abs() < 1.0);
    }
}
