#!/usr/bin/env python3
"""Relativity-off experiment reference (2026-09-04).

Hand-parse one GPS record from the live BRDC file and evaluate the periodic
relativistic clock term F*e*sqrtA*sin(Ek) with the IS-GPS-200 Kepler
pipeline (12 Newton iterations seeded at Mk, exactly the form of
gps::broadcast::kepler_e), plus the full broadcast clock with and without
the term. Output is the JSON fixture tests/fixtures/relativity/
gps_rel_eval.json, which pins the Rust relativistic_periodic_s /
sat_clock on that record (src/gps/broadcast.rs tests).

Usage: python3 scripts/relativity_reference.py ["G07 2026 09 04 06 00 00"]
         > tests/fixtures/relativity/gps_rel_eval.json
Regenerating against a NEWER brdc_latest.rnx changes the numbers (the
record embedded in the fixture is the provenance); the Rust test hardcodes
the 2026-09-04 values, so regenerate only together with that test.
No numpy; pure python; never touches the radio.
"""
import json, math, sys
MU = 3.986005e14
F = -4.442807633e-10
C = 299792458.0
WEEK = 604800.0
path = "/Volumes/Radiator 8TB/gnss/observations/brdc_latest.rnx"
lines = open(path).read().splitlines()
hdr = next(i for i, l in enumerate(lines) if "END OF HEADER" in l)
want = sys.argv[1] if len(sys.argv) > 1 else "G07 2026 09 04 06 00 00"
idx = next(i for i in range(hdr + 1, len(lines)) if lines[i].startswith(want))
rec = lines[idx:idx + 8]
def fl(s, a, b):
    return float(s[a:b].replace("D", "e"))
def f(l, j):
    return fl(rec[l + 1], 4 + j * 19, 4 + (j + 1) * 19)
ln = rec[0]
y, mo, d, h, mi, s = (int(ln[4:8]), int(ln[9:11]), int(ln[12:14]), int(ln[15:17]), int(ln[18:20]), int(ln[21:23]))
def jdn(y, m, d):
    a = (14 - m) // 12; yy = y + 4800 - a; mm = m + 12 * a - 3
    return d + (153 * mm + 2) // 5 + 365 * yy + yy // 4 - yy // 100 + yy // 400 - 32045
gps_epoch = jdn(1980, 1, 6)
days = jdn(y, mo, d) - gps_epoch
toc = (days % 7) * 86400.0 + h * 3600 + mi * 60 + s
eph = dict(
    af0=fl(ln, 23, 42), af1=fl(ln, 42, 61), af2=fl(ln, 61, 80),
    crs=f(0, 1), delta_n=f(0, 2), m0=f(0, 3),
    cuc=f(1, 0), e=f(1, 1), cus=f(1, 2), sqrt_a=f(1, 3),
    toe=f(2, 0), cic=f(2, 1), omega0=f(2, 2), cis=f(2, 3),
    i0=f(3, 0), crc=f(3, 1), omega=f(3, 2), omega_dot=f(3, 3),
    idot=f(4, 0), week=f(4, 2), tgd=f(5, 2), toc=toc,
)
assert 0.5 < eph["i0"] < 1.2, "radians unit sanity (i0 ~0.95 rad)"
def wrap(tk):
    if tk > WEEK / 2: tk -= WEEK
    elif tk < -WEEK / 2: tk += WEEK
    return tk
def kepler(m, ecc):
    ek = m
    for _ in range(12):
        ek -= (ek - ecc * math.sin(ek) - m) / (1.0 - ecc * math.cos(ek))
    return ek
def ek_at(t):
    a = eph["sqrt_a"] * eph["sqrt_a"]
    n0 = math.sqrt(MU / (a * a * a))
    tk = wrap(t - eph["toe"])
    mk = eph["m0"] + (n0 + eph["delta_n"]) * tk
    return kepler(mk, eph["e"])
def rel(t):
    return F * eph["e"] * eph["sqrt_a"] * math.sin(ek_at(t))
def clock(t):
    dt = wrap(t - eph["toc"])
    poly = eph["af0"] + eph["af1"] * dt + eph["af2"] * dt * dt
    return poly + rel(t) - eph["tgd"]
def poly_minus_tgd(t):
    dt = wrap(t - eph["toc"])
    return eph["af0"] + eph["af1"] * dt + eph["af2"] * dt * dt - eph["tgd"]
epochs = [eph["toe"], eph["toe"] + 900.0, eph["toe"] + 2700.0]
out = {
  "_provenance": ("Generated by hand-parsing one live GPS record from "
     "/Volumes/Radiator 8TB/gnss/observations/brdc_latest.rnx (BKG mixed BRDC, "
     "radians, file dated 2026-09-04 09:10 UTC) with a pure-python IS-GPS-200 "
     "Kepler pipeline: mu=3.986005e14, F=-4.442807633e-10, 12 Newton iterations "
     "seeded at Mk (the same form as gps::broadcast::kepler_e). The verbatim "
     "record lines are embedded so the fixture is self-contained. Pins the "
     "Rust relativistic_periodic_s (relativity-off experiment, "
     "CLOCK_BIAS_RELATIVITY_OFF_PRNS) and sat_clock on that record at three "
     "epochs. Regenerate: python3 scripts/relativity_reference.py > "
     "tests/fixtures/relativity/gps_rel_eval.json (hardcoded twins live in "
     "src/gps/broadcast.rs relativistic_term_pins_the_python_cross_check_on_live_g07)."),
  "constants": {"mu": MU, "f_rel": F, "c": C},
  "record": {"label": ln[:3], "rinex_lines": rec, "toe": eph["toe"], "toc": eph["toc"],
             "e": eph["e"], "sqrt_a": eph["sqrt_a"], "tgd": eph["tgd"],
             "amplitude_s": F * eph["e"] * eph["sqrt_a"],
             "amplitude_m": F * eph["e"] * eph["sqrt_a"] * C},
  "evaluations": [
     {"t_sow": t, "ek_rad": ek_at(t), "rel_s": rel(t), "rel_m": rel(t) * C,
      "clock_s": clock(t), "clock_minus_rel_s": poly_minus_tgd(t)} for t in epochs],
}
print(json.dumps(out, indent=1))
